name: date_countdown
description: A Flutter app for keeping track of the days since a given date.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  remove_alpha_ios: true
  image_path: "assets/icon/icon1024.png"
  image_path_ios: "assets/icon/icon1024_ios.png"
